### ISSUE TITLE
Write a tweet

### ISSUE THREAD

**Issue by ai** [lutien/postcss-extract-value#2]
Could you write a tweet in English about your plugin with small screenshot? I want to retweet it in PostCSS twitter account.

Also, it is a great plugin. After some work it could become a killer feature for PostCSS :). @ben-eb told me some ideas about for better CSS minifing on top of your plugin.

**Comment by lutien** [comment]
Thank you :) I think a tweet is not already necessary because of it https://twitter.com/nucliweb/status/740544079898025984 Or not?

**Comment by ai** [comment]
Let's tweet again on next feature release 😊

**Comment by lutien** [comment]
https://twitter.com/lutien2/status/762285039518412800
